### PR TITLE
exact-match-users-detail-page #385

### LINKED ISSUE #385: Use exact match for user details page
**Describe the bug**
The pages available by non-exact keys, e.g. `arkid15r1` vs `arkid15f`

**To Reproduce**
https://nest.owasp.dev/community/users/arkid15r1

**Expected behavior**
The page should be available by exact user key only, e.g. https://nest.owasp.dev/community/users/arkid15r

**Screenshots**

Screenshot 2025-01-08 at 5 38 33 PM

### PR DESCRIPTION
**Pull request by yashgoyal0110**
fixes #385

### CODE REVIEW

**Review by Rajgupta36 — CHANGES_REQUESTED** [review]
instead of map and match exact value use filter that already available in api.ts/fetchAlgoliaData function

File: frontend/src/pages/UserDetails.tsx [hunk 1]
```diff
@@ -25,11 +25,12 @@ const UserDetailsPage: React.FC = () => {
     const fetchUserData = async () => {
       try {
         const { hits } = await fetchAlgoliaData('users', userKey, 1)
```
Comment (Rajgupta36) [inline frontend/src/pages/UserDetails.tsx:27]: pass userkey here simple

**Review by Rajgupta36 — CHANGES_REQUESTED** [review]

**Comment by yashgoyal0110** [comment]
@Rajgupta36 i have made the changes, please have a look now

**Review by arkid15r — APPROVED** [review]
LGTM 👍 

Thanks @yashgoyal0110 ! And @Rajgupta36 for review

**Comment by yashgoyal0110** [comment]
@arkid15r thanks for opportunity😄
