### PR TITLE
Bug/fix scroll on Project Health Score click

### LINKED ISSUE #2034: Fix scroll on Project Health Score click
**Describe the bug**
Every project page now shows Health Score at the top right corner. Clicking that badge should scroll to `Issues trend` card. Currently it scrolls, but not to the correct spot. It should show proper card right after the header on autoscroll.

**Are you going to work on fixing this?**

- [ ] Yes
- [x] No

**Screenshots**

https://github.com/user-attachments/assets/bff72a8b-a932-44f5-9479-a87e4f812384

### PR DESCRIPTION
**Pull request by divyanshu-vr**
## Proposed change
Fixed scroll on Project Health Score click

Resolves #2034 

Fixed the bug and added tests.

Feature- we can add a feature where pressing Enter or Spacebar on the badge scrolls down. I've optimized it for so, if we ever need to do it in the future.

## Checklist

- [ ] I've read and followed the [contributing guidelines](https://github.com/OWASP/Nest/blob/main/CONTRIBUTING.md).
- [x] I've run `make check-test` locally; all checks and tests passed.

### CODE REVIEW

File: frontend/src/components/MetricsScoreCircle.tsx [hunk 1]
```diff
@@ -1,18 +1,33 @@
...
+
   return (
     <Tooltip content={'Current Project Health Score'} placement="top">
+      {/* eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions */}
       <div
-        className={`group relative flex h-14 w-14 flex-col items-center justify-center rounded-full shadow-md transition-all duration-300 hover:scale-105 hover:shadow-lg ${scoreStyle}`}
+        className={`group relative flex h-14 w-14 flex-col items-center justify-center rounded-full shadow-md transition-all duration-300 hover:scale-105 hover:shadow-lg ${scoreStyle} ${
+          onClick ? 'cursor-pointer' : ''
+        }`}
+        onClick={handleClick}
```
[the remark this answers is not in the document]
Comment (divyanshu-vr) [reply frontend/src/components/MetricsScoreCircle.tsx]: we can leave this for a future update to add functionality for keyboard.

**Comment by divyanshu-vr** [comment]
Hi @kasya, @arkid15r,
I’ve fixed the bug and also left scope to add keyboard handler functionality in the future. Here’s the video attached below showing the implementation.


https://github.com/user-attachments/assets/4dae5c57-0322-43c1-ba6e-ad22966c903d

**Review by kasya — CHANGES_REQUESTED** [review]
@divyanshu-vr Hi! There are some conflicts with your current changes. Please resolve those so I could review the PR 👍🏼

**Comment by divyanshu-vr** [comment]
> @divyanshu-vr Hi! There are some conflicts with your current changes. Please resolve those so I could review the PR 👍🏼

Hi @kasya, I've resolved the conflicts. You can review the PR now 👍

File: frontend/src/components/CardDetailsPage.tsx [hunk 2]
```diff
@@ -10,12 +10,9 @@ import {
 } from '@fortawesome/free-solid-svg-icons'
 import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
 import upperFirst from 'lodash/upperFirst'
-import Link from 'next/link'
-import { useRouter } from 'next/navigation'
-import { useSession } from 'next-auth/react'
```
Comment (kasya) [inline frontend/src/components/CardDetailsPage.tsx]: Why did you remove these? We still reference them in the code. Please return - the page crashes now

File: frontend/src/components/CardDetailsPage.tsx [hunk 3]
```diff
@@ -10,12 +10,9 @@ import {
...
-import type { ExtendedSession } from 'types/auth'
```
Comment (kasya) [inline frontend/src/components/CardDetailsPage.tsx:16]: Same with this

File: frontend/src/components/CardDetailsPage.tsx [hunk 4]
```diff
@@ -96,9 +93,15 @@ const DetailsCard = ({
                 </button>
               )}
             {IS_PROJECT_HEALTH_ENABLED && type === 'project' && healthMetricsData.length > 0 && (
-              <Link href="#issues-trend">
-                <MetricsScoreCircle score={healthMetricsData[0].score} />
-              </Link>
+              <a
```
Comment (kasya) [inline frontend/src/components/CardDetailsPage.tsx]: I don't think we use regular anchor tag anywhere else. Is there a way to make it work with `Link` for consistency? 
Because it seems that the main issue was with incorrect offset, right?

**Review by kasya — CHANGES_REQUESTED** [review]
This works! I did left some comments about implementation though and also you need to update your PR - you removed a bunch of stuff that we still use in the `CardDetailsPage` component.

File: frontend/src/components/CardDetailsPage.tsx (hunk 2 above)
Comment (divyanshu-vr) [reply frontend/src/components/CardDetailsPage.tsx]: i must've accidentally removed these during resolving conflicts, ill revert back to how it was before.

File: frontend/src/components/CardDetailsPage.tsx (hunk 3 above)
Comment (divyanshu-vr) [reply frontend/src/components/CardDetailsPage.tsx:16]: I'll revert back to how it was before.

File: frontend/src/components/CardDetailsPage.tsx (hunk 4 above)
Comment (divyanshu-vr) [reply frontend/src/components/CardDetailsPage.tsx]: Hmm, you're right! I'll have to look into it more to make it work with `Link`, as i was failing to do so before. Give me some time ill get back to you asap. Sorry for the inconvenience caused.

Comment (divyanshu-vr) [reply frontend/src/components/CardDetailsPage.tsx]: > I don't think we use regular anchor tag anywhere else. Is there a way to make it work with `Link` for consistency? Because it seems that the main issue was with incorrect offset, right?

hi @kasya, I’ve replaced the anchor tag with Link and it works fine now. ill send the push soon.

Also, do you think `utils\scrollToAnchor.ts` is unnecessary?
From my perspective, the incorrect offset issue was happening because the scroll didn’t account for the header/nav height — the offset itself was somewhat fine, but the content was getting hidden under the header. But `utils\scrollToAnchor.ts` handles:
- Dynamic heading height calculations. If the header is changed in future it wont affect the scroll offset.
- offset calculations: yOffset = -headingHeight - 80
- Coordinating with AnchorTitle component's existing scroll logic

If you prefer, I can take a simpler approach and redo this entirely. In that case, we can close this PR and I’ll start a fresh one.

**Review by kasya — APPROVED** [review]
@divyanshu-vr Thanks for working on this!

I refactored MetricsScoreCircle to handle click logic internally instead of wrapping with `Link` components. Also added onClick and clickable props for flexible usage, improved accessibility with proper button roles and keyboard navigation. This provides cleaner architecture and better separation of concerns.

**Comment by divyanshu-vr** [comment]
> @divyanshu-vr Thanks for working on this!
> 
> I refactored MetricsScoreCircle to handle click logic internally instead of wrapping with `Link` components. Also added onClick and clickable props for flexible usage, improved accessibility with proper button roles and keyboard navigation. This provides cleaner architecture and better separation of concerns.

These changes make it even better  thank you, @kasya ! I had implemented keyboard navigation initially but later removed it, as I was asked on the issue page to leave it for a future enhancement. Do you have any specific feedback for me? I’m new to OSS and still learning best practices.
