### PR TITLE
Fix Project Metrics dashboard responsiveness on small screens

### LINKED ISSUE #3368: Project Metrics dashboard is not responsive on smaller screens
**Describe the bug**
The Project Metrics dashboard page does not render correctly on smaller screen sizes. Content appears cramped and partially cut off, making metrics hard to read and interact with on mobile

**To Reproduce**

1. Go to  
   `http://localhost:3000/projects/dashboard/metrics`
2. Open the page on a mobile device or enable mobile view in browser dev tools
3. Observe the layout of the Project Health Metrics section

**Expected behavior**
- The Metrics dashboard should be fully responsive across screen sizes.
- Metric cards should resize, wrap, or stack properly on smaller screens.
- Text and values should remain readable without overflowing or being clipped.

**Are you going to work on fixing this?**

- [x] Yes
- [ ] No

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by anurag2787**
## Proposed change
This PR improves the responsiveness of the Project Metrics dashboard on smaller screens. It updates the layout to adapt properly on mobile by replacing table-style views with responsive cards, improving spacing and readability, and adding a mobile-friendly sorting control.

Resolves #3368 

## Before
image

## After
image

## Checklist

- [x] **Required:** I followed the [contributing workflow](https://github.com/OWASP/Nest/blob/main/CONTRIBUTING.md#contributing-workflow)
- [x] **Required:** I verified that my code works as intended and resolves the issue as described
- [x] **Required:** I ran `make check-test` locally: all warnings addressed, tests passed
- [ ] I used AI for code, documentation, tests, or communication related to this PR

### CODE REVIEW

**Comment by anurag2787** [comment]
Hi @kasya I’ve added a new card-based layout for the mobile view since the table layout doesn’t really work well on smaller screens  and one more thing like while implementing sorting for mobile view i got a bit unsure about the UI. Right now, when a user taps on a field like Stars, it sorts in descending order first, and tapping it again switches to ascending.
Does this interaction make sense for mobile, or do you think there’s a better way to handle sorting direction on smaller screens?

**Comment by anurag2787** [comment]
@kasya @arkid15r 
And also while working on this i noticed that [Project Dashboard](http://localhost:3000/projects/dashboard) is also not responsive 
image
Same with http://localhost:3000/projects/dashboard/metrics/social-osint-agent Page
image

Hi, I’ve created a separate issue for this #3445 about the Project Health Dashboard if you feel this should be handled here instead i will work on it in this pr itself

File: frontend/src/app/projects/dashboard/metrics/page.tsx [hunk 1]
```diff
@@ -268,8 +291,46 @@ const MetricsPage: FC = () => {
...
+                {
+                  title: 'Sort by',
+                  items: MOBILE_SORT_FIELDS.map((field) => ({
+                    label: field.label,
+                    key: field.key,
+                  })),
+                },
+                {
+                  title: 'Actions',
+                  items: [{ label: 'Clear sorting', key: 'clear-sort' }],
```
Comment (ahmedxgouda) [inline frontend/src/app/projects/dashboard/metrics/page.tsx]:
```suggestion
                  title: 'Reset',
                  items: [{ label: 'Reset Sorting', key: 'reset-sort' }],
```

File: frontend/src/app/projects/dashboard/metrics/page.tsx [hunk 2]
```diff
@@ -28,6 +35,14 @@ const FIELD_MAPPING = {
...
 type OrderKey = keyof typeof FIELD_MAPPING
 
+const MOBILE_SORT_FIELDS = [
+  { label: 'Score', key: 'score' },
+  { label: 'Stars', key: 'stars' },
+  { label: 'Forks', key: 'forks' },
+  { label: 'Contributors', key: 'contributors' },
+  { label: 'Last checked', key: 'createdAt' },
+] as const
+
```
Comment (ahmedxgouda) [inline frontend/src/app/projects/dashboard/metrics/page.tsx]: It is better to have a field for each ordering (e.g score_desc, score_asc).

File: frontend/src/app/projects/dashboard/metrics/page.tsx [hunk 3]
```diff
@@ -57,6 +72,14 @@ const buildOrderingWithTieBreaker = (primaryOrdering: Record<string, Ordering>)
...
   },
 ]
+
+const getNextOrderKey = (fieldKey: OrderKey, currentOrderKey: string) => {
+  if (!currentOrderKey || currentOrderKey.replace('-', '') !== fieldKey) {
+    return `-${fieldKey}`
+  }
+  return currentOrderKey.startsWith('-') ? fieldKey : `-${fieldKey}`
+}
+
```
Comment (ahmedxgouda) [inline frontend/src/app/projects/dashboard/metrics/page.tsx]: This should be removed after you add a field for each ordering

File: frontend/src/app/projects/dashboard/metrics/page.tsx [hunk 4]
```diff
@@ -268,8 +291,46 @@ const MetricsPage: FC = () => {
...
+                  items: [{ label: 'Clear sorting', key: 'clear-sort' }],
+                },
+              ]}
+              selectionMode="single"
+              selectedKeys={urlKey ? [urlKey.startsWith('-') ? urlKey.slice(1) : urlKey] : []}
+              selectedLabels={
+                urlKey
+                  ? [MOBILE_SORT_FIELDS.find((f) => f.key === urlKey.replace('-', ''))?.label || '']
+                  : []
+              }
```
Comment (ahmedxgouda) [inline frontend/src/app/projects/dashboard/metrics/page.tsx]: A lot of complexity in the code can be avoided if we use a field for each ordering.

File: frontend/src/app/projects/dashboard/metrics/page.tsx [hunk 5]
```diff
@@ -268,8 +291,46 @@ const MetricsPage: FC = () => {
...
+              onAction={(key: string) => {
+                if (key === 'clear-sort') {
+                  handleSort(null)
+                  return
+                }
+
+                const nextOrderKey = getNextOrderKey(key as OrderKey, urlKey)
```
Comment (ahmedxgouda) [inline frontend/src/app/projects/dashboard/metrics/page.tsx]: We won't need this after the update of the ordering fields.

Comment (anurag2787) [reply frontend/src/app/projects/dashboard/metrics/page.tsx]: Done

File: frontend/src/app/projects/dashboard/metrics/page.tsx (hunk 3 above)
Comment (anurag2787) [reply frontend/src/app/projects/dashboard/metrics/page.tsx]: Done

File: frontend/src/app/projects/dashboard/metrics/page.tsx [hunk 6]
```diff
@@ -267,9 +292,42 @@ const MetricsPage: FC = () => {
...
+              }
+              onAction={(key: string) => {
+                if (key === 'reset-sort') {
+                  handleSort(null)
+                  return
+                }
+
+                handleSort(key)
+              }}
+            />
```
[the remark this answers is not in the document]
Comment (anurag2787) [reply frontend/src/app/projects/dashboard/metrics/page.tsx:248]: I agree there is an inconsistency but this change is intentional we are standardizing the mobile dropdown to single criterion sorting consistent with how sorting already works on desktop.

**Comment by kasya** [comment]
> Thanks for working on this. Also I think it is better to make the same design for all screens instead of having a table for large screens and a list of cards for mobile screens, we should use your new design for all screens. With this, not also the user will see the same UI/UX in different devices, but the code will be cleaner and more simple. 

I agree! I like this new design 👍🏼 Let's make it the same for all screen sizes.

File: package-lock.json
Comment (kasya) [inline package-lock.json:1]: @anurag2787 Did you mean to push this? 🤔

Comment (anurag2787) [reply package-lock.json:1]: Sorry about that it was pushed by mistake. I’ll remove it from the pr

**Comment by anurag2787** [comment]
image
