### PR TITLE
fix: align 'Show more' button in Projects page-#1329

### LINKED ISSUE #1329: Show more button misaligned
**Describe the bug**
Show more button is misaligned in project details component

**To Reproduce**
Check Topics and Top Contributors section in Projects page

**Expected behavior**
Should be aligned to left like other elements in card 

**Are you going to work on fixing this?**

- [x] Yes
- [ ] No

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by adithya-naik**
---

### Description:

This PR fixes the misalignment of the **"Show more / Show less"** button in the **Top Contributors** section on the Projects page.  
The button was previously off alignment compared to other elements in the card, as described in issue [#1329](https://github.com/OWASP/Nest/issues/1329).

---

### Changes Made:
- Refactored the button into a reusable React component.
- Ensured proper alignment using Tailwind CSS utility classes.
- Verified the fix visually in the running development environment.

---

### Related Issue:  
Closes #1329

---

### ✅ Checklist:
- [x] UI issue reproduced and confirmed
- [x] Fix applied and tested locally
- [x] PR linked to the issue
- [x] Code follows the repo's style guidelines
- [x] Contributing guidelines followed

### CODE REVIEW

**Comment by adithya-naik** [comment]
Hi @arkid15r 👋 I've submitted a PR for the issue I was assigned. Please take a moment to review it. If everything looks good and works as expected, feel free to merge it. Thank you! 🙂

File: frontend/src/components/TopContributorsList.tsx [hunk 1]
```diff
@@ -67,21 +67,23 @@ const TopContributorsList = ({
...
-            <>
-              Show more <FontAwesomeIcon icon={faChevronDown} className="ml-1" />
-            </>
-          )}
-        </Button>
+        <div className="mt-4 flex justify-start">
+          <Button
+            disableAnimation
+            onPress={toggleContributors}
+            className="bg-blue-50 hover:bg-blue-100 dark:bg-blue-900/20 dark:hover:bg-blue-900/30 text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300 border border-blue-200 dark:border-blue-800 rounded-md px-4 py-2 font-medium transition-colors"
```
[the remark this answers is not in the document]
Comment (adithya-naik) [reply frontend/src/components/TopContributorsList.tsx]: Is this ready to merge? Or waiting for review?

[the remark this answers is not in the document]
Comment (adithya-naik) [reply frontend/src/components/TopContributorsList.tsx]: You suggested creating a separate component for the button, but after reviewing the usage, I noticed that the styles are only applied in these two specific cases. Based on my current understanding, there don’t appear to be any additional use cases, so I felt creating a separate component might be unnecessary. Therefore, I decided to proceed without it and have committed the changes accordingly.

[the remark this answers is not in the document]
Comment (arkid15r) [reply frontend/src/components/TopContributorsList.tsx]: @adithya-naik it looks like I had the same idea for a previous PR trying to address this issue -- https://github.com/OWASP/Nest/pull/1358#pullrequestreview-2762562841

Normally, if you have it in more that 1 place you should consider making it a separate entity.

[the remark this answers is not in the document]
Comment (adithya-naik) [reply frontend/src/components/TopContributorsList.tsx]: As of my knowledge it's not required to create a separate component and is the same opinion of @coderabbitai isn't it?

**Comment by adithya-naik** [comment]
I will submit u the PR with the requested changes shortly @arkid15r

**Comment by adithya-naik** [comment]
hey can u review this @arkid15r   /@kasya

**Comment by adithya-naik** [comment]
> Could you add tests for the new component? I bumped this to 10 points.

Thanks for the update! @arkid15r 🙌  
I'm still a beginner and currently not familiar with writing tests using tools like React Testing Library or Jest. I’ve tried exploring it, but I’m not yet confident enough to implement proper tests for this component.

If it’s okay and you or someone else is able to take care of the tests for now, that would be really helpful. I’ll definitely try to learn this soon and contribute better next time 🙇‍♂️

Thank you for your understanding!

File: frontend/src/components/ShowMoreButton.tsx [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+const ShowMoreButton = ({
+  isExpanded,
+  onToggle,
+  showMoreText = 'Show more',
+  showLessText = 'Show less',
+}: {
+  isExpanded: boolean
+  onToggle: () => void
+  showMoreText?: string
+  showLessText?: string
```
Comment (arkid15r) [inline frontend/src/components/ShowMoreButton.tsx]: I believe `onToggle` is the only needed param here.

The state should be handled internally and the showMore/showLess text is going to be the same

**Review by arkid15r — CHANGES_REQUESTED** [review]
@kasya any suggestions regarding the UI? Should we keep the previous look?

File: frontend/src/components/ShowMoreButton.tsx (hunk 2 above)
Comment (adithya-naik) [reply frontend/src/components/ShowMoreButton.tsx]: Sure @arkid15r ! Based on the latest usage, I'll remove the unnecessary props:

❌ Can be removed:
- `showMoreText`
- `showLessText`

✅ Required for current usage:
- `isExpanded`
- `onToggle`

interface ToggleButtonProps {
  isExpanded: boolean  // ✅ Required - tells button what to display
  onToggle: () => void // ✅ Required - tells parent when clicked
}

Both props are necessary for the component to work properly!

I’ll update the code accordingly and raise a PR shortly.

Comment (arkid15r) [reply frontend/src/components/ShowMoreButton.tsx]: **I believe onToggle is the only needed param here.**

Why do you need to keep `isExpanded`?

Comment (adithya-naik) [reply frontend/src/components/ShowMoreButton.tsx]: Alright @arkid15r, I'll handle isExpanded internally and commit the changes. Hopefully, this will be the final update — fingers crossed! 😄

**Comment by adithya-naik** [comment]
Hi @arkid15r,

I've made the following improvements:

- **Removed** the `isExpanded` prop – it's now handled internally.
- **Removed** `showMoreText` and `showLessText` – using fixed labels instead.
- **Added** internal `useState` for managing the expanded state.
- **Updated** the parent components to only pass the `onToggle` callback.
- **Simplified** the interface – now only `onToggle` is required.

Let me know if this works or if you'd like further changes!

**Comment by adithya-naik** [comment]
Hi @arkid15r,  
Is there anything I might be missing or anything else you'd like me to update?  
Happy to make any final changes if needed!

**Comment by adithya-naik** [comment]
Hi @arkid15r, I noticed that @coderabbitai referenced this PR in another one (#1908), and I'm not quite sure what's happening here. Could you please help me understand the context or explain what exactly is going on?

**Review by kasya — CHANGES_REQUESTED** [review]
@adithya-naik Could you also add tests for this newly created component - `ShowMoreButton`?

**Comment by adithya-naik** [comment]
> > Could you add tests for the new component? I bumped this to 10 points.
> 
> Thanks for the update! @arkid15r 🙌  
> I'm still a beginner and currently not familiar with writing tests using tools like React Testing Library or Jest. I’ve tried exploring it, but I’m not yet confident enough to implement proper tests for this component.
> 
> If it’s okay and you or someone else is able to take care of the tests for now, that would be really helpful. I’ll definitely try to learn this soon and contribute better next time 🙇‍♂️
> 
> Thank you for your understanding!
> 



@kasya as i mentioned I don't know how to add test cases as iam a beginner .
Hope you understand! ☺️

**Comment by adithya-naik** [comment]
Hi @arkid15r, @kasya,
Just checking in—any updates on this? Let me know if anything is pending from my side.

File: frontend/src/components/ShowMoreButton.tsx [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+    onToggle()
+  }
+
+  return (
+    <div className="mt-4 flex justify-start">
+      <Button
+        type="button"
+        disableAnimation
+        onPress={handleToggle}
+        className="flex items-center bg-transparent text-blue-400"
```
Comment (kasya) [inline frontend/src/components/ShowMoreButton.tsx]: I thought the original issue was about misalignment.. but the only change is that you put the code for the button in a separate component (good for reusing it 👍🏼 ). But the alignment is still off, since those classes were not changed. 
Screenshot 2025-07-30 at 9 34 54 PM
Screenshot 2025-07-30 at 9 34 38 PM


The fix is actually a simple one line update 😅 
```suggestion
        className="px-0 flex items-center bg-transparent text-blue-400"
```

**Review by kasya — CHANGES_REQUESTED** [review]

File: frontend/src/components/ShowMoreButton.tsx (hunk 3 above)
Comment (adithya-naik) [reply frontend/src/components/ShowMoreButton.tsx]: That’s a neat and efficient fix 😄 Appreciate the suggestion — makes the UI cleaner with just a small change. Thanks, @Kasya! 🙌

**Comment by adithya-naik** [comment]
Also, could you please add the gssoc25 label along with the existing one? That’ll help track contributions better. Thanks!

**Comment by kasya** [comment]
> Also, could you please add the gssoc25 label along with the existing one? That’ll help track contributions better. Thanks!

The issue has the label - the PR doesn't need to have it.
I also pushed changes - make sure you run `make-check` and commit changed files. It is required by contributing guidelines for OWASP Nest.

**Comment by adithya-naik** [comment]
Thanks for the clarification, @Kasya! 🙌
Since you already pushed some changes, could you also please commit the updated files after running make-check? That would help align it with the contributing guidelines. Appreciate your support!

**Review by kasya — APPROVED** [review]
