### PR TITLE
fix: improve Sort By dropdown styling consistency

### LINKED ISSUE #1372: Refactor "Sort By" Dropdown Styling for Better UI Consistency
**Description**:  
Currently, when the "Sort By" dropdown is clicked, the selected option (e.g., *Relevance*) receives a blue-colored outline which feels inconsistent with the overall UI design. Additionally, the dropdown box styling does not align well with the rest of the interface and looks visually unappealing.

**Expected Behavior**:
- The dropdown should have a cleaner, more integrated look with the existing UI.
- Focus/active states should be styled to match the design system (e.g., neutral borders or subtle shadows instead of default blue outlines).

**Suggested Changes**:
- Remove or customize the blue outline using `focus:outline-none` and apply custom focus styles if needed.
- Redesign the dropdown container with padding, border, and background styles that fit better with the current theme (dark/light mode support if applicable).
- Ensure accessibility is maintained after style changes.

**Screenshots (if applicable)**:

https://github.com/user-attachments/assets/deec5c93-0cd1-4861-bfbd-b4a1c3b204c4

### PR DESCRIPTION
**Pull request by mrkeshav-05**
- Remove blue outline and inconsistent hover backgrounds
- Add proper focus/active states styles to match the design system
- Improve light/dark mode theme integration
- Fix trigger background blending issues

Fixes #1372

Before Changes:
| Light Mode | Dark Mode |
|--------|--------|
| image | image |
| image | image | 

After Changes:
| Light Mode | Dark Mode |
|--------|--------|
| image | image |
| image | image |

### CODE REVIEW

File: frontend/src/components/SortBy.tsx
Comment (kasya) [inline frontend/src/components/SortBy.tsx:1]: Can we make sure the padding on right and left side match? Right now it's way bigger on the left:

Image

Image

File: frontend/src/components/SortBy.tsx [hunk 1]
```diff
@@ -38,7 +46,8 @@ const SortBy = ({
             <SelectItem
               key={option.key}
               classNames={{
-                base: 'text-sm hover:bg-[#D1DBE6] dark:hover:bg-[#454545] rounded-none px-3 py-0.5',
+                base: 
+                  'text-sm text-gray-700 dark:text-gray-300 hover:bg-transparent dark:hover:bg-[#404040] focus:bg-gray-100 dark:focus:bg-[#404040] focus:outline-none rounded-sm px-3 py-2 cursor-pointer transition-colors duration-150 data-[selected=true]:bg-blue-50 dark:data-[selected=true]:bg-blue-900/20 data-[selected=true]:text-blue-600 dark:data-[selected=true]:text-blue-400 data-[focus=true]:bg-gray-100 dark:data-[focus=true]:bg-[#404040]',
```
[the remark this answers is not in the document]
Comment (kasya) [reply frontend/src/components/SortBy.tsx]: @mrkeshav-05 This seems like a valid point. Could you check it? All comments made by Reviewing bots should be resolved before actual review request 👌🏼

**Review by kasya — CHANGES_REQUESTED** [review]
Thanks @mrkeshav-05 for working on this!
Left some comments. 

Also, please run `make check` and commit suggested changes - this is required by contributing guidelines in OWASP Nest project.

File: frontend/src/components/SortBy.tsx
Comment (mrkeshav-05) [reply frontend/src/components/SortBy.tsx:1]: Fixed the padding issue - added balanced `px-3` to the container

Screenshot 2025-10-06 at 3 44 19 PM
image

**Comment by mrkeshav-05** [comment]
@kasya Thank you for the review!

I've addressed the feedback:
- Ran `make check` - all checks passed successfully
- Fixed the padding imbalance issue - added balanced `px-3` to the container
- Added "hover:bg-transparent dark:hover:bg-transparent"  for Light and Dark mode


screenshot of the improved style:
| Light Mode | Dark Mode |
|--------|--------|
| image | image | 

Code is ready for review.

File: frontend/src/components/SortBy.tsx [hunk 2]
```diff
@@ -15,17 +15,21 @@ const SortBy = ({
   return (
     <div className="flex items-center gap-2">
       {/* Sort Attribute Dropdown */}
-      <div className="inline-flex h-12 items-center rounded-lg bg-gray-200 dark:bg-[#323232]">
+      <div className="inline-flex h-12 items-center rounded-lg border border-gray-300 bg-gray-100 px-3 shadow-sm transition-all duration-200 hover:shadow-md dark:border-gray-600 dark:bg-[#323232]">
```
Comment (kasya) [inline frontend/src/components/SortBy.tsx]: I know the classes seem right, but we should have the same padding that we see on the frontend and not just the classes.
I don't think these are the same padding on right and left side 🤔 Clearly there's much more space after the caret on the right.

Which means that these classes should be different:

```suggestion
      <div className="inline-flex h-12 items-center rounded-lg border border-gray-300 bg-gray-100 pl-3 shadow-sm transition-all duration-200 hover:shadow-md dark:border-gray-600 dark:bg-[#323232]">
```
To only keep the padding (we don't need padding after caret to match the left side).
Before and after:

Image
Image

Comment (mrkeshav-05) [reply frontend/src/components/SortBy.tsx]: Yes, you're right! Previously with `px-3`, the right side had too much padding because it added:
- `px-3` (padding on both sides) = 12px right padding
- Plus the natural spacing from the dropdown icon/caret

These are the after changes:
image image

In this padding of `12px` are on the both side.
