### PR TITLE
fix: dark mode toggle logic

### LINKED ISSUE #1153: Dark Mode Toggle Needs Better UX  Behavior
**Description:**

The dark mode toggle button has an incorrect initial state. When the website loads in light mode, the toggle button appears in the "on" position instead of "off." Clicking it switches to dark mode, but the button behavior is reversed—when dark mode is enabled, the toggle appears as "off" instead of "on." Additionally, the logo should update accordingly.

**Steps to Reproduce:**

- Load the website (it starts in light mode).
- Observe that the dark mode toggle button is in the "on" position instead of "off."
- Click the toggle to enable dark mode.
- Notice that the toggle switches to the "off" position instead of "on."

https://github.com/user-attachments/assets/fd91134d-bbe2-4885-93a0-9ec1b0ebbadc

**Expected Behavior:**

- The toggle button should be in the "off" position when the site loads in light mode.
- When dark mode is enabled, the toggle should move to the "on" position.
- The logo should update correctly based on the selected theme.

### PR DESCRIPTION
**Pull request by M-ayank2005**
Resolves #1153 

## Description:  
This PR improves the **ModeToggle** component by optimizing theme persistence and enhancing UI behavior. The changes ensure a seamless dark mode experience.

### ModeToggle Component:  
- Optimized the **theme toggle logic** for better user experience.  
- Enhanced **button styling and transitions** for a smoother UI experience.  

## Why This is Needed:  
- Ensures **a better user experience** by respecting system dark mode preferences.   

## Testing & Validation:  
✔️ Verified UI updates across different screen sizes.  
✔️ Ensured `localStorage` properly persists theme selection.  
✔️ Checked TypeScript type safety for component props.  
✔️ Tested theme switching behavior with system preferences.

### CODE REVIEW

File: frontend/src/components/ModeToggle.tsx [hunk 1]
```diff
@@ -25,28 +25,29 @@ function ModeToggle({ className }: { className?: string }) {
...
-        </label>
+        <button
+          onClick={darkModeHandler}
+          className="relative h-10 w-10 transform overflow-hidden rounded-full border border-gray-300 shadow-sm transition-all duration-200 hover:shadow-md focus:outline-none focus:ring-1 focus:ring-gray-600 active:scale-95 dark:border-gray-600"
+          aria-label={dark ? 'Enable light mode' : 'Enable dark mode'}
+        >
+          <div className="absolute inset-0 bg-gray-100 transition-colors duration-300 dark:bg-gray-800"></div>
+          <div className="absolute inset-0 flex items-center justify-center">
+            <FontAwesomeIcon
+              icon={!dark ? faMoon : faSun}
```
Comment (arkid15r) [inline frontend/src/components/ModeToggle.tsx]:
```suggestion
              icon={dark ? faSun : faMoon}
```

File: frontend/src/components/ModeToggle.tsx [hunk 2]
```diff
@@ -25,28 +25,29 @@ function ModeToggle({ className }: { className?: string }) {
...
-            checked={!dark}
-            onChange={darkModeHandler}
-            aria-label={dark ? 'Enable light mode' : 'Enable dark mode'}
-          />
-
-          <div className="peer h-6 w-11 rounded-full bg-gray-200 after:absolute after:left-[2px] after:top-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-white after:transition-all after:content-[''] peer-checked:after:translate-x-full peer-checked:after:border-white dark:border-gray-600 dark:bg-gray-700"></div>
-        </label>
+        <button
+          onClick={darkModeHandler}
+          className="relative h-10 w-10 transform overflow-hidden rounded-full border border-gray-300 shadow-sm transition-all duration-200 hover:shadow-md focus:outline-none focus:ring-1 focus:ring-gray-600 active:scale-95 dark:border-gray-600"
```
Comment (arkid15r) [inline frontend/src/components/ModeToggle.tsx]: Could you make it look more simple? It seems there is unnecessary border when the button is in focus. Also for the light theme the background seems inconsistent comparing to what we have for the dark theme behavior.

**Review by arkid15r — CHANGES_REQUESTED** [review]
Thanks for addressing this! Please look into the following comments when you get a chance:

File: frontend/src/components/ModeToggle.tsx (hunk 1 above)
Comment (M-ayank2005) [reply frontend/src/components/ModeToggle.tsx]: @arkid15r  i have fixed this in my new commit

File: frontend/src/components/ModeToggle.tsx (hunk 2 above)
Comment (M-ayank2005) [reply frontend/src/components/ModeToggle.tsx]: Thanks for the feedback! I've made the requested changes. I have made the toggle button match with the other button such as sponser to have a consistent ui also i have applied same hover effect as in other buttons . Please review and let me know if any further modifications are needed.

**Comment by M-ayank2005** [comment]
@arkid15r   I've made the requested changes. I have made the toggle button match with the other button such as sponser and star to have a consistent ui also i have applied same hover effect as in other buttons . Please review and let me know if any further modifications are needed.

**Review by arkid15r — APPROVED** [review]
LGTM
