### PR TITLE
Restrict access to Module Issues page

### LINKED ISSUE #4018: Anyone is able to access the Module Issues page in Mentorship Portal
Community & Support: [LinkedIn Group](https://www.linkedin.com/groups/14656108/) · [Slack #project-nest](https://owasp.slack.com/archives/project-nest)

Active project leaders: Arkadii Yakovets -- [GitHub](https://github.com/arkid15r/) · [LinkedIn](https://www.linkedin.com/in/arkid15r/) · [Slack](https://owasp.slack.com/team/U060W3NKLTF); Kate Golovanova -- [GitHub](https://github.com/kasya/) · [LinkedIn](https://www.linkedin.com/in/kate-golovanova/) · [Slack](https://owasp.slack.com/team/U07PWB1JZ6Z)

[Contributing](https://github.com/owasp/nest/blob/main/CONTRIBUTING.md) · [Code of Conduct](https://github.com/owasp/nest/blob/main/CODE_OF_CONDUCT.md) · [GSoC Mentors](https://github.com/owasp/nest/blob/main/MENTORS.md)

---

**Describe the bug**
The Module Issues page inside the Mentorship Portal is currently accessible to non-program-admin users also
By directly visiting the URL, users can access the issues page of a module even when they are not program admins.

**To Reproduce**

Go to 'https://nest.owasp.org/my/mentorship/programs/owasp-nest-google-summer-of-code-2025/modules/owasp-nest-mentorship-portal/issues'

**Expected behavior**
Only Program Admins should be able to access the Module Issues page in the Mentorship Portal.

**Are you going to work on fixing this?**

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by anurag2787**
## Proposed change
This PR fixes an access control issue in the Mentorship Portal where the Module Issues page could be accessed by anyone using the direct URL now the page is restricted so that only Program Admins and Mentors can view it

Resolves #4018

## Checklist

- [x] **Required:** I followed the [contributing workflow](https://github.com/OWASP/Nest/blob/main/CONTRIBUTING.md#contributing-workflow)
- [x] **Required:** I verified that my code works as intended and resolves the issue as described
- [x] **Required:** I ran `make check-test` locally: all warnings addressed, tests passed
- [ ] I used AI for code, documentation, tests, or communication related to this PR

### CODE REVIEW

**Comment by anurag2787** [comment]
Hi @kasya the PR is ready for review

while working on this issue I explored the session logic and noticed a bug where if someone is assigned as a mentor the isLeader value also becomes true I created an issue for this #4283 if possible please assign this issue to me

I also created another issue #4277 because a query is still being called even when the user is unauthorized which seems unnecessary

File: frontend/src/components/AccessDeniedDisplay.tsx
Comment (anurag2787) [inline frontend/src/components/AccessDeniedDisplay.tsx:1]: As this file has been created here so we can also use it in #3483

File: frontend/src/app/my/mentorship/programs/[programKey]/modules/[moduleKey]/issues/[issueId]/page.tsx [hunk 1]
```diff
@@ -100,10 +108,26 @@ const ModuleIssueDetailsPage = () => {
...
 
+  if (status === 'loading') {
+    return <LoadingSpinner />
+  }
+
+  if (!isProjectLeader && !isMentor) {
+    return (
+      <AccessDeniedDisplay
+        title="Access Denied"
+        message="Only project leaders and mentors can access this page."
```
Comment (kasya) [inline frontend/src/app/my/mentorship/programs/[programKey]/modules/[moduleKey]/issues/[issueId]/page.tsx]: @anurag2787 I'm actually not sure if this is correct.
The issues should be available to program admins and mentors. the user can be a project leader but not an admin for the program 🤔 .

On the backend we check access by doing `user_has_access()` and that method checks for program admins or module mentors.

File: frontend/src/components/AccessDeniedDisplay.tsx
Comment (kasya) [inline frontend/src/components/AccessDeniedDisplay.tsx:1]: @anurag2787 Could you update the layout for this page so it's not scrollable?

**Comment by anurag2787** [comment]
Hi @kasya the pr is ready for review
