### PR TITLE
fix: handle _leaflet_pos TypeError on chapters map

### LINKED ISSUE #4286: Bug: Leaflet map throws TypeError on Chapters page
Community & Support: [LinkedIn Group](https://www.linkedin.com/groups/14656108/) · [Slack #project-nest](https://owasp.slack.com/archives/project-nest)

Active project leaders: Arkadii Yakovets -- [GitHub](https://github.com/arkid15r/) · [LinkedIn](https://www.linkedin.com/in/arkid15r/) · [Slack](https://owasp.slack.com/team/U060W3NKLTF); Kate Golovanova -- [GitHub](https://github.com/kasya/) · [LinkedIn](https://www.linkedin.com/in/kate-golovanova/) · [Slack](https://owasp.slack.com/team/U07PWB1JZ6Z)

[Contributing](https://github.com/owasp/nest/blob/main/CONTRIBUTING.md) · [Code of Conduct](https://github.com/owasp/nest/blob/main/CODE_OF_CONDUCT.md) · [GSoC Mentors](https://github.com/owasp/nest/blob/main/MENTORS.md)

---

**Describe the bug**
While browsing the Chapters page, I noticed a JavaScript 
error appearing in the browser console when the map loads.

Error:
Uncaught TypeError: cannot read properties of 
undefined (reading '_leaflet_pos')

**To Reproduce**

1. Go to https://nest.owasp.org/chapters
2. Apply the "Date Created' filter
3. Then select a country from the country filter
4. Open browser console (F12)
5. Observe the TypeError in console

**Expected behavior**
The map should load without any console errors.

**Are you going to work on fixing this?**

- [x] Yes
- [] No

**Screenshots**

Image

**Desktop (please complete the following information):**

- OS: [windows ]
- Browser [chrome]
- Version [145]

**Smartphone (please complete the following information):**
**Additional context**

### PR DESCRIPTION
**Pull request by taditharun**
## Proposed change

Resolves #4286

While browsing the chapters page I noticed a JavaScript error 
in the browser console. The error occurs when the Date Created 
filter is applied and a country is selected from the dropdown.

Error:
Uncaught TypeError: Cannot read properties of undefined 
(reading '_leaflet_pos')

The issue is in the MapZoomControl component — leaflet tries 
to read the map pane position during zoom transition before 
the map container is fully initialized.

Wrapped the map control logic in a try/catch block to handle 
this gracefully.

## Type of change

- [x] Bug fix

## Checklist
- [x] I was assigned to this issue before starting work
- [x] I have read the contributing guidelines  
- [x]  I ran make check-test locally (failures are pre-existing and unrelated to my changes)
- [x] My changes do not break any existing functionality

### CODE REVIEW

**Comment by taditharun** [comment]
hiii @anurag2787 , Thanks for the review! Will fix the root cause and run make check-test before pushing.

**Comment by taditharun** [comment]
Fixed!, Added null checks for map container in the cleanup effect and MapViewUpdater as well. Ran ChapterMap tests locally  40/40 passed.

**Comment by taditharun** [comment]
Hi @arkid15r and  @anurag2787  Fixed the root cause and removed try,catch completely and kept only proper null checks for map container. All 40 ChapterMap tests passing locally with 0 errors. I don't have Algolia keys locally so unable to test the full search flow  could you verify on your end?

**Comment by anurag2787** [comment]
> Hi @arkid15r and @anurag2787 Fixed the root cause and removed try,catch completely and kept only proper null checks for map container. All 40 ChapterMap tests passing locally with 0 errors. I don't have Algolia keys locally so unable to test the full search flow could you verify on your end?

The error is still occurring on my end also for Algolia you can get a free API key from https://www.algolia.com

**Comment by taditharun** [comment]
Hi @anurag2787 !, Got Algolia keys set up and tested locally. The TypeError is fixed  applying Date Created filter and selecting a country shows no errors in console. Screenshot attached. Could you please re-review?

Screenshot 2026-03-20 213814

**Comment by taditharun** [comment]
Hi @anurag2787 , just wanted to add  I also tested on the live production site at nest.owasp.org/chapters and the bug is still reproducible there. Selecting Albania triggers the same Uncaught TypeError: Cannot read properties of undefined 
(reading '_leaflet_pos'). My fix resolves this locally. This confirms the fix is needed on production too!!

Screenshot 2026-03-20 224054

File: frontend/src/components/ChapterMap.tsx [hunk 1]
```diff
@@ -19,6 +19,7 @@ const MapZoomControl = ({ isMapActive }: { isMapActive: boolean }) => {
   const zoomControlRef = useRef<L.Control.Zoom | null>(null)
   useEffect(() => {
     if (!map) return
+    if (!map.getContainer()) return
```
Comment (anurag2787) [inline frontend/src/components/ChapterMap.tsx]:
```suggestion
    if (!map || !map.getContainer()) return
```
We can consolidate these checks into a single guard

File: frontend/src/components/ChapterMap.tsx [hunk 2]
```diff
@@ -73,7 +74,9 @@ const MapViewUpdater = ({
 
   useEffect(() => {
     if (!map) return
+    try{
```
Comment (anurag2787) [inline frontend/src/components/ChapterMap.tsx]: this doesn’t seem necessary since the issue is already handled by the guards so you can remove it.

**Comment by taditharun** [comment]
Hi @anurag2787 , consolidated the guards into a single check. All 21 ChapterMap tests passing . make check-test fails due to a pre-existing SyntaxError in mentorship_sync_module_issues_test.py line 241 which I didn't touch  raising a separate issue for that. Please re-review!
Screenshot 2026-03-21 223251

**Comment by taditharun** [comment]
Hi @anurag2787 , just a gentle reminder to re-review when you get a chance. All changes have been addressed!

**Comment by anurag2787** [comment]
Hi @taditharun i am still able to reproduce the error by sorting on date created and then applying a country filter
Its looks like guard doesn’t fix the issue it just hiding it so instead of this we should fix the root cause of the error and the error seems like coming because of race condition between React re-renders and Leaflet animations

**Comment by taditharun** [comment]
Hi @anurag2787! Fixed the root cause added an isMounted ref to prevent Leaflet operations after component unmounts, and added map._loaded check in MapViewUpdater to prevent race condition during re-renders. Could you please re-review?

**Comment by taditharun** [comment]
Hi @kasya  and @anurag2787! Ready for review.
Removed the try/catch and isMounted ref and fixed it properly with null checks. First check if map exists, then get the container and check that too before doing anything. This stops the _leaflet_pos error at the root.
All 40 ChapterMap tests passing locally. make check-test fails but its all pre-existing errors  like Terraform, mypy and the mentorship_sync_module_issues_test.py syntax error, nothing I touched.thankyou!!

**Comment by taditharun** [comment]
Hi @kasya !, Thank you so much for merging this and for fixing the check-test issues. I'll make sure to run make check-test properly on my feature branch before every push from now on. Sorry for the trouble!
