### PR TITLE
Fix: Add rounded corners to map component for UI consistency

### LINKED ISSUE #4311: Map Component Missing Rounded Corners
Community & Support: [LinkedIn Group](https://www.linkedin.com/groups/14656108/) · [Slack #project-nest](https://owasp.slack.com/archives/project-nest)

Active project leaders: Arkadii Yakovets -- [GitHub](https://github.com/arkid15r/) · [LinkedIn](https://www.linkedin.com/in/arkid15r/) · [Slack](https://owasp.slack.com/team/U060W3NKLTF); Kate Golovanova -- [GitHub](https://github.com/kasya/) · [LinkedIn](https://www.linkedin.com/in/kate-golovanova/) · [Slack](https://owasp.slack.com/team/U07PWB1JZ6Z)

[Contributing](https://github.com/owasp/nest/blob/main/CONTRIBUTING.md) · [Code of Conduct](https://github.com/owasp/nest/blob/main/CODE_OF_CONDUCT.md) · [GSoC Mentors](https://github.com/owasp/nest/blob/main/MENTORS.md)

---

### Issue: Map Component Missing Rounded Corners

**Describe the bug**
The map component does not have rounded corners, while most other UI components use rounded borders. This creates an inconsistent visual style.

**To Reproduce**

1. Go to the OWASP Nest homepage
2. Scroll to the section containing the map
3. Observe that the map container has no rounded corners

**Expected behavior**

The map component should use the same border-radius as other UI components to maintain visual consistency.

**Screenshots**

Image

**Are you going to work on fixing this?**

* [x] Yes
* [ ] No

### PR DESCRIPTION
**Pull request by Saurabh-2607**
## Proposed change

Resolves #4311

The map component currently does not have rounded corners, while most other UI elements in the interface use rounded borders. This creates a small visual inconsistency in the design.

This PR adds the same `border-radius` used across other UI components to the map container so that it aligns with the overall design system.

### Changes made
- Added `rounded-lg` to the map container.
- Ensured the map respects the rounded container edges.
- Maintained consistency with existing UI components.

### Result
Before
image

After
Screenshot 2026-03-19 065708

## Checklist

- [x] **Required:** I followed the [contributing workflow](https://github.com/OWASP/Nest/blob/main/CONTRIBUTING.md#contributing-workflow)
- [x] **Required:** I verified that my code works as intended and resolves the issue as described
- [x] **Required:** I ran `make check-test` locally: all warnings addressed, tests passed
- [ ] I used AI for code, documentation, tests, or communication related to this PR

### CODE REVIEW

File: frontend/src/components/ChapterMap.tsx [hunk 1]
```diff
@@ -179,7 +179,7 @@ const ChapterMap = ({
   return (
     <section
       aria-label="Chapter Map"
-      className="relative"
+      className="relative overflow-hidden rounded-lg"
```
Comment (kasya) [inline frontend/src/components/ChapterMap.tsx]: I think I remembered now why we removed the rounded corners at some point.
With rounded corners there's this lighter "border" that gets pretty noticeable in corners. 

Image
Image

Do you think we could get rid of this and still keep rounded corners?

Comment (Saurabh-2607) [reply frontend/src/components/ChapterMap.tsx]: Let me Check

**Comment by Saurabh-2607** [comment]
@kasya Resolved the Issue about the a border on the edges
image
image
