### PR TITLE
fix: resolve footer layout break between 647px and 764px

### LINKED ISSUE #3480: Footer layout breaks between 647px and 764px screen width
**Describe the bug**
The footer layout breaks in mid-size screen widths (roughly 647px–764px).  
In this range, the footer columns (`OWASP Nest`, `Resources`, `Community`, `OWASP`) do not stack and align correctly.

**To Reproduce**

1. Open the [Nest website  ](https://nest.owasp.org/)
2. Open browser DevTools  
3. Set the viewport width between **647px and 764px**  
4. Scroll to the footer  
5. Observe the broken spacing and misaligned sections  

**Expected behavior**
 The footer should be fully responsive

**Are you going to work on fixing this?**

- [ ] Yes
- [x] No

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by stealthwhizz**
## Proposed change

Resolves #3480

The footer layout breaks at mid-size screen widths (647px–764px) because `sm:gap-20` (80px) is too large for the 2-column grid at the `sm` breakpoint (640px+).

**Fix:** Replace `sm:gap-20` with `sm:gap-x-10 sm:gap-y-6` for balanced spacing in the 2-column layout, and add `md:gap-x-20` to restore the larger horizontal gap at the `md` breakpoint (768px+).

## Checklist

- [x] **Required:** I followed the [contributing workflow](https://github.com/OWASP/Nest/blob/main/CONTRIBUTING.md#contributing-workflow)
- [x] **Required:** I verified that my code works as intended and resolves the issue as described
- [x] **Required:** I ran `make check-test` locally: all warnings addressed, tests passed
- [ ] I used AI for code, documentation, tests, or communication related to this PR

image

### CODE REVIEW

**Review by kasya — COMMENTED** [review]
hi @stealthwhizz! Thanks for working on this!

I'm not sure I understand the full issue correctly, though I can see you've made some good improvements on the UI 👍🏼 
Before:

Image
After:

Image

I'm just going to ask @anurag2787 to also take a look, since he was the one who opened the issue. 
@anurag2787 could you review this PR?

**Review by anurag2787 — CHANGES_REQUESTED** [review]
Hi @stealthwhizz it looks good to me overall 👍
Just one small request: could you also check the medium screen layout for the footer? Right now the gap between the footer sections feels a bit too large on medium screens. It would be nice if the spacing shrinks or adapts to the screen size so it doesn’t look a bit odd there.

https://github.com/user-attachments/assets/ac2d22f7-a359-4d87-90a8-56a47f32d7de

**Comment by stealthwhizz** [comment]
Now the horizontal gap grows more gradually:
small → 10px,
medium → 14px,
large+ → 20px (80px), which matches the original intent.

@anurag2787 Can you look into this

**Review by anurag2787 — CHANGES_REQUESTED** [review]
Hi @stealthwhizz, thanks for adjusting the spacing!
One more small thing i noticed after this change the dropdown arrows in the footer look a bit inconsistent in alignment Could you also take a look at that?

Image

**Comment by stealthwhizz** [comment]
@anurag2787 All changes are now up in the branch.

**Comment by anurag2787** [comment]
> @anurag2787 All changes are now up in the branch.

Hi @stealthwhizz I can still see dropdown arrows inconsistent alignment

image

**Comment by stealthwhizz** [comment]
On it

**Comment by stealthwhizz** [comment]
@anurag2787 can you look into this 

https://github.com/user-attachments/assets/985bd7ec-bec5-4a2f-ae79-b6486ce9dc53

File: frontend/src/components/Footer.tsx [hunk 1]
```diff
@@ -29,25 +29,23 @@ export default function Footer() {
...
-        <div className="grid w-full sm:grid-cols-2 sm:gap-20 md:grid-cols-4">
+        <div className="grid w-full sm:grid-cols-2 sm:gap-x-10 sm:gap-y-6 md:grid-cols-4 md:gap-x-14 lg:gap-x-20">
           {footerSections.map((section: Section) => (
             <div key={section.title} className="flex flex-col gap-4">
               {/*link*/}
               <Button
                 disableAnimation
                 onPress={() => toggleSection(section.title)}
-                className="flex w-full items-center justify-between rounded-md bg-transparent pl-0 text-left text-lg font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-500 lg:cursor-default"
+                className="flex w-full items-center justify-start gap-2 rounded-md bg-transparent pl-0 text-left text-lg font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-500 lg:cursor-default"
```
Comment (anurag2787) [inline frontend/src/components/Footer.tsx]: Looks Good Just a small change so that Mobile layout doesn't change

Image

```suggestion
                className="flex w-full items-center justify-between md:justify-start md:gap-2 rounded-md bg-transparent pl-0 text-left text-lg font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-500 lg:cursor-default"
```

**Comment by stealthwhizz** [comment]
@anurag2787 check once
