### PR TITLE
Fixed 404 flash on mentee page

### LINKED ISSUE #4238: 404 Flash When Opening Mentee Page in Mentorship Portal
Community & Support: [LinkedIn Group](https://www.linkedin.com/groups/14656108/) · [Slack #project-nest](https://owasp.slack.com/archives/project-nest)

Active project leaders: Arkadii Yakovets -- [GitHub](https://github.com/arkid15r/) · [LinkedIn](https://www.linkedin.com/in/arkid15r/) · [Slack](https://owasp.slack.com/team/U060W3NKLTF); Kate Golovanova -- [GitHub](https://github.com/kasya/) · [LinkedIn](https://www.linkedin.com/in/kate-golovanova/) · [Slack](https://owasp.slack.com/team/U07PWB1JZ6Z)

[Contributing](https://github.com/owasp/nest/blob/main/CONTRIBUTING.md) · [Code of Conduct](https://github.com/owasp/nest/blob/main/CODE_OF_CONDUCT.md) · [GSoC Mentors](https://github.com/owasp/nest/blob/main/MENTORS.md)

---

**Describe the bug**
When opening a mentee page in the mentorship portal, a 404 page briefly flashes before the actual page loads. After the flash, the correct mentee page renders normally.

**To Reproduce**

Go to 'http://localhost:3000/my/mentorship/programs/[programme-name]/modules/[module-name]/mentees/[mentee-username]'

**Expected behavior**
The mentee page should load directly without showing a 404

**Are you going to work on fixing this?**

- [x] Yes
- [ ] No

**Screenshots**
https://github.com/user-attachments/assets/08f7c9cb-ae92-4ac7-90fa-b210ecff2e47

### PR DESCRIPTION
**Pull request by anurag2787**
## Proposed change
Fixes an issue where a 404 page briefly flashed before the mentee page loaded. The page now loads directly without showing the temporary 404.

Resolves #4238

## Checklist

- [ ] **Required:** I followed the [contributing workflow](https://github.com/OWASP/Nest/blob/main/CONTRIBUTING.md#contributing-workflow)
- [x] **Required:** I verified that my code works as intended and resolves the issue as described
- [x] **Required:** I ran `make check-test` locally: all warnings addressed, tests passed
- [ ] I used AI for code, documentation, tests, or communication related to this PR

### CODE REVIEW

**Comment by anurag2787** [comment]
Hi @arkid15r the pr is ready for review

File: frontend/src/app/my/mentorship/programs/[programKey]/modules/[moduleKey]/mentees/[menteeKey]/page.tsx [hunk 1]
```diff
@@ -71,7 +74,19 @@ const MenteeProfilePage = () => {
...
 
-  if (isLoading) return <LoadingSpinner />
+  if (isLoading || !hasReceivedData) {
+    return <LoadingSpinner />
+  }
+
+  if (error) {
+    return (
+      <ErrorDisplay
+        statusCode={500}
```
Comment (arkid15r) [inline frontend/src/app/my/mentorship/programs/[programKey]/modules/[moduleKey]/mentees/[menteeKey]/page.tsx:69]: Why server 500 error here?

File: frontend/src/app/my/mentorship/programs/[programKey]/modules/[moduleKey]/mentees/[menteeKey]/page.tsx [hunk 2]
```diff
@@ -71,7 +74,19 @@ const MenteeProfilePage = () => {
     }))
   }, [menteeIssuesData])
 
-  if (isLoading) return <LoadingSpinner />
+  if (isLoading || !hasReceivedData) {
```
Comment (arkid15r) [inline frontend/src/app/my/mentorship/programs/[programKey]/modules/[moduleKey]/mentees/[menteeKey]/page.tsx]: How come `isLoading` is not enough?

Comment (anurag2787) [reply frontend/src/app/my/mentorship/programs/[programKey]/modules/[moduleKey]/mentees/[menteeKey]/page.tsx]: Actually here the Apollo works with cache and network so on the render there is a small moment where loading becomes false even before the network response actually comes specially when there is no cache data so at that time the data is becoming null so their is a 404 flash coming

File: frontend/src/app/my/mentorship/programs/[programKey]/modules/[moduleKey]/mentees/[menteeKey]/page.tsx (hunk 1 above)
Comment (anurag2787) [reply frontend/src/app/my/mentorship/programs/[programKey]/modules/[moduleKey]/mentees/[menteeKey]/page.tsx:69]: I am updated the statuscode

File: frontend/src/app/my/mentorship/programs/[programKey]/modules/[moduleKey]/mentees/[menteeKey]/page.tsx (hunk 2 above)
Comment (kasya) [reply frontend/src/app/my/mentorship/programs/[programKey]/modules/[moduleKey]/mentees/[menteeKey]/page.tsx]: @anurag2787 That's a great point, but there's a simpler solution than what you have proposed.
We prev. had the same issue with other mentorship portal pages (might be other pages still have this wrong setup). 
The problem is that we don't really need useEffect + useState on this page. We can just read straight from `data` we receive.

I'll push a small update to simplify this . Feel free to look at my solution and check if there are other pages that might need the same fix 👍🏼
