### PR TITLE
removed the repeated code

### LINKED ISSUE #2952: useSearchPage.ts hook has the same code repeated.
**Describe the bug**
Two branches in a conditional structure should not have exactly the same implementation [typescript:S1871](https://sonarcloud.io/organizations/owasp-1/rules?open=typescript%3AS1871&rule_key=typescript%3AS1871)

**To Reproduce**

1. Go to frontend/src/hooks/useSearchPage.ts
2. remove the extract line of code

**Expected behavior**
we will prevent DRY principle in code.

**Are you going to work on fixing this?**

- [X] Yes
- [ ] No

**Additional context**
[Sonal Issue](https://sonarcloud.io/project/issues?impactSeverities=MEDIUM&issueStatuses=OPEN%2CCONFIRMED&id=OWASP_Nest&open=AZVOfcyX8k-bWeSEH1Ms&tab=code)

### PR DESCRIPTION
**Pull request by anirudhprmar**
## Proposed change

Resolves #2952 

This file contained a repeated line of code which i removed.

## Checklist

- [X] **Required:** I read and followed the [contributing guidelines](https://github.com/OWASP/Nest/blob/main/CONTRIBUTING.md)
- [X] **Required:** I ran `make check-test` locally and all tests passed
- [ ] I used AI for code, documentation, or tests in this PR

### CODE REVIEW

File: frontend/src/hooks/useSearchPage.ts [hunk 1]
```diff
@@ -57,8 +57,6 @@ export function useSearchPage<T>({
         (searchQuery !== searchQueryParam || sortBy !== sortByParam || order !== orderParam)
       ) {
         setCurrentPage(1)
-      } else if (searchQuery !== searchQueryParam) {
-        setCurrentPage(1)
       }
```
Comment (kasya) [inline frontend/src/hooks/useSearchPage.ts:62]: This is not exactly a correct fix.
the first if and check for `searchQuery !== searchQueryParam` would only work for projects, but we also need to keep the logic for other places. 

I pushed something to refactor the code so that we don't have repeated code, but still keep the same logic.

Comment (anirudhprmar) [reply frontend/src/hooks/useSearchPage.ts:62]: okay, i get it. We're not just doing this for the projects but for all the other places too.
