### PR TITLE
Fix tooltip conflicts for duplicate contributors

### LINKED ISSUE #1058: Fix project tooltip issue
> @arkid15r, this issues also persist for contributors section as well.
> 
> https://github.com/user-attachments/assets/26e44fc5-bb6b-4896-9d5d-3c76781a7f60 

 _Originally posted by @yashgoyal0110 in [#997](https://github.com/OWASP/Nest/issues/997#issuecomment-2708190947)_

### PR DESCRIPTION
**Pull request by rishyym0927**
Resolves #1058

This PR resolves an issue where tooltips would behave incorrectly if the same contributor appeared in multiple cards. The fix appends a unique identifier to the tooltip id, ensuring each tooltip instance is distinct.

1. Added a uniqueKey prop to ContributorAvatar.
2. Modified the tooltip id to include uniqueKey.
3. Updated parent component usage to pass a unique identifier.

https://github.com/user-attachments/assets/fb1ff195-e5b5-44c7-8d19-3194e2fce785

### CODE REVIEW

File: frontend/src/components/ContributorAvatar.tsx [hunk 1]
```diff
@@ -39,7 +40,7 @@ const ContributorAvatar = memo(({ contributor }: ContributorProps) => {
 
   return (
     <Tooltip
-      id={`avatar-tooltip-${login}`}
+      id={`avatar-tooltip-${login}-${uniqueKey}`}
```
Comment (arkid15r) [inline frontend/src/components/ContributorAvatar.tsx:43]: It seems this composite key should include the project part too. This way we avoid the same bug when same contributor is on the same position within multiple projects on the same page. This case is very low probability but still can happen. You can create a separate issue for that as it requires more effort (index update may be needed)/

**Review by arkid15r — APPROVED** [review]
LGTM

File: frontend/src/components/ContributorAvatar.tsx (hunk 1 above)
Comment (rishyym0927) [reply frontend/src/components/ContributorAvatar.tsx:43]: Yes I guess the probability is very less but still it can happen again. Though this implementation will work but as you we need update the indexes and create a more robust unique key. I was thinking of using Math.random() but again ig its not a good practise!!

**Review by kasya — APPROVED** [review]
