### PR TITLE
Fix modal overflow and improve responsiveness on  on small screens of contribute page

### LINKED ISSUE #3369: Contributor “Read more” dialog overflows on mobile and small screens
**Describe the bug**
On the OWASP Nest Contributor page, when clicking on the "Read more" button, a dialog/modal opens but the content overflows the viewport on smaller screen sizes. The dialog is not fully responsive, causing text to be cut off and making it difficult to read or interact with the content properly.

**To Reproduce**

1. Go to the OWASP Nest Contributor page
2. Click on a Contributor card
3. Click on the "Read more" button
4. Observe the opened dialog on a small screen or mobile view
5. Notice that the content overflows and is not properly scrollable or responsive

**Expected behavior**
The dialog should be fully responsive across all screen sizes. The content should fit within the viewport, with proper scrolling if needed, and no text or buttons should overflow outside the dialog.

**Are you going to work on fixing this?**

- [x] Yes
- [ ] No

Image

### PR DESCRIPTION
**Pull request by Isha-upadhyay**
## Proposed change

Resolves #3369 

This PR fixes an issue on the **OWASP Nest Contributor page** where the **“Read more” dialog overflowed the viewport on mobile and small screen devices**, making content difficult to read and interact with.

### What was changed
- Made the modal layout fully responsive across all screen sizes
- Ensured long titles and descriptions wrap correctly instead of overflowing
- Added proper internal scrolling for modal content on smaller viewports
- Adjusted modal height constraints to prevent viewport overflow
- Improved overall usability without changing any backend logic or data flow

### Why this change
On smaller screens, the dialog content exceeded the viewport height, causing text and actions to be cut off.  
This update ensures the modal remains readable and accessible on mobile devices while preserving the existing desktop experience.

---

## Screenshots
Screenshot 2026-01-17 202809

---

## Testing

- Verified modal behavior locally using the frontend development server
- Tested with long titles and content on both desktop and mobile viewports
- Confirmed content scrolls correctly and no elements overflow outside the modal

---

## Checklist

- [x] **Required:** I followed the contributing workflow
- [x] **Required:** I verified that my code works as intended and resolves the issue
- [x] **Required:** I ran relevant local checks for this UI-only change
- [ ] I used AI for code, documentation, tests, or communication related to this PR

### CODE REVIEW

File: frontend/src/components/Modal.tsx [hunk 1]
```diff
@@ -15,45 +21,152 @@ const DialogComp: React.FC<ModalProps> = ({
...
+              text-white
+              hover:bg-gray-700
+              focus:outline-none
+              focus:ring-2
+              focus:ring-gray-500
+              focus:ring-offset-2
+              dark:bg-gray-700
+              dark:hover:bg-gray-600
+              dark:focus:ring-gray-600
+            "
```
Comment (kasya) [inline frontend/src/components/Modal.tsx:169]: Please run `make check-test` next time - we don't wrap classes like this and our linters would have picked this up and updated the formatting.
I'll push a change to update this 👌🏼

Comment (Isha-upadhyay) [reply frontend/src/components/Modal.tsx:169]: I did run `make check-test` locally and the relevant frontend checks passed.

The failures I saw were limited to YAML / line-ending related hooks (CRLF vs LF) which are environment-specific and unrelated to the modal UI change, so I didn’t include them in this PR.
