### PR TITLE
Fix overflow and layout issues in UserCard component on Community page

### LINKED ISSUE #982: Add wrap on Community page
The company information displayed on the Community page is not wrapping correctly, causing overflow and layout issues

Image

### PR DESCRIPTION
**Pull request by end-9214**
Resolves #982 

This PR addresses issue #982 by ensuring the company information displayed on the Community page wraps correctly, preventing overflow and layout issues. The changes were made in the UserCard component.

### CODE REVIEW

**Review by kasya — COMMENTED** [review]
@end-9214 Please run local checks to address CI/CD issues

File: frontend/src/components/UserCard.tsx [hunk 1]
```diff
@@ -27,8 +27,8 @@ const UserCard = ({ avatar, name, company, button }: UserCardProps) => {
           <h3 className="line-clamp-1 text-lg font-semibold text-gray-900 group-hover:text-blue-500 dark:text-white sm:text-xl">
             {name}
           </h3>
-          <p className="mt-1 line-clamp-1 text-sm text-gray-600 dark:text-gray-400 sm:text-base">
-            {company || ''}
+          <p className="mt-1 text-sm text-gray-600 dark:text-gray-400 sm:text-base">
+            <span style={{ wordWrap: 'break-word', whiteSpace: 'pre-wrap' }}>{company || ''}</span>
```
Comment (arkid15r) [inline frontend/src/components/UserCard.tsx]: Is it possible to fix issue using existing CSS classes instead of the custom `style`?

Comment (end-9214) [reply frontend/src/components/UserCard.tsx]: yes

**Comment by end-9214** [comment]
Used existing CSS classes.

**Review by kasya — APPROVED** [review]
Nice!
