### PR TITLE
Fixed cursor pointer tags

### LINKED ISSUE #2672: Add pointer cursor to Languages/Topics
**Description** currently, the Languages and Topics items on the projects page (e.g., https://nest.owasp.org/projects/coraza-web-application-firewall) show the default cursor.

**Proposed Change** adding a cursor: pointer style to these items to indicate they are interactive.

**Assignee** Please assign this issue to me as I am ready to work on a PR for this immediately.

### PR DESCRIPTION
**Pull request by SidharthxNST**
**Proposed change** -:

Added Cursor for Languages

Resolves #2672 

**## PR Description - :**
 when the click is disabled it will not show the cursor .. I have created it as a dynamic value .

## Checklist

- [ ✓ ]  I've read and followed the [contributing guidelines](https://github.com/OWASP/Nest/blob/main/CONTRIBUTING.md).

- [ ✓ ] I've run `make check-test` locally; all checks and tests passed.

### CODE REVIEW

**Comment by SidharthxNST** [comment]
@kasya I did the change which the Sonar comment  addressed

File: frontend/src/components/ToggleableList.tsx [hunk 1]
```diff
@@ -39,7 +39,7 @@ const ToggleableList = ({
         {(showAll ? items : items.slice(0, limit)).map((item) => (
           <button
             key={item}
```
Comment (kasya) [inline frontend/src/components/ToggleableList.tsx]: @SidharthxNST I'd recommend either to use something else, or a composite key - I'm not sure if we enforce uniqueness of these 🤔

**Review by kasya — CHANGES_REQUESTED** [review]

File: frontend/src/components/ToggleableList.tsx (hunk 1 above)
Comment (SidharthxNST) [reply frontend/src/components/ToggleableList.tsx]: Hi @kasya I have Updated the key to use a composite key (${item}-${index}) to avoid collisions when items are not guaranteed to be unique... And ya sorry I did some accidental changes I have removed that too

**Comment by SidharthxNST** [comment]
@arkid15r  I have resolved the conflicts , will add the tests for my changes

**Review by kasya — DISMISSED** [review]
@SidharthxNST Thank you!
