### PR TITLE
Fixed sporadic 404 flash 

### LINKED ISSUE #2386: Fix sporadic 404 flash on /about page
**Describe the bug**

It's rarely reproducible but it 100% exists. When you open https://nest.owasp.org/about page it sometimes shows quick 404 page while still loading the contents and then presents the loaded content.

**To Reproduce**

Open https://nest.owasp.org/about many times. Be lucky

**Expected behavior**

No 404 page shown

**Are you going to work on fixing this?**

- [ ] Yes
- [x] No

**Screenshots**

No screenshot, sorry.

### PR DESCRIPTION
**Pull request by anurag2787**
Fix #2386 

## Description
Fixed briefly flashes of 404 error before loading the actual content

## Checklist

- [x] I've read and followed the [contributing guidelines](https://github.com/OWASP/Nest/blob/main/CONTRIBUTING.md).
- [x] I've run `make check-test` locally; all checks and tests passed.

### CODE REVIEW

**Comment by anurag2787** [comment]
I am not able to reproduce the issue (i think i am not that much lucky 😅) but I noticed that it can happen due to a race condition between useQuery and useEffect or may also occur if the data is undefined but due to the isLoading condition it assumes loading has completed and renders the 404

**Comment by kasya** [comment]
@anurag2787 could you attach the issue to this PR?

**Comment by anurag2787** [comment]
Have Attached the issue, Sorry for inconvenience 

> @anurag2787 could you attach the issue to this PR?

File: frontend/src/app/about/page.tsx [hunk 1]
```diff
@@ -51,24 +51,26 @@ const leaders = {
...
-        hasFullName: true,
-        key: projectKey,
-        limit: 24,
-      },
-    }
-  )
+  const {
+    data: topContributorsResponse,
+    error: topContributorsRequestError,
+    loading: topContributorsLoading,
```
Comment (kasya) [inline frontend/src/app/about/page.tsx:65]: Nice 👍🏼
