### PR TITLE
Fixed 404 flash when opening repository pages

### LINKED ISSUE #3732: 404 Flash When Opening Repository Pages
**Describe the bug**
When opening a repository page directly using a URL like: `https://nest.owasp.org/organizations/[org-key]/repositories/[repo-key` he page briefly shows a 404 error before the actual repository page loads.
[Example ](https://nest.owasp.org/organizations/juice-shop/repositories/juice-shop) Even though the page eventually loads correctly, this quick flash of the 404 screen feels broken

**Expected behavior**
The repository page should load directly, without ever showing a 404 state.

**Are you going to work on fixing this?**

- [x] Yes
- [ ] No

**Screenshots**
https://github.com/user-attachments/assets/e9040b9c-cd60-474a-8194-28785f6408e8

### PR DESCRIPTION
**Pull request by anurag2787**
## Proposed change
This PR fixes a brief 404 screen that appears when directly opening a repository URL

Resolves #3732

## Checklist

- [x] **Required:** I followed the [contributing workflow](https://github.com/OWASP/Nest/blob/main/CONTRIBUTING.md#contributing-workflow)
- [x] **Required:** I verified that my code works as intended and resolves the issue as described
- [x] **Required:** I ran `make check-test` locally: all warnings addressed, tests passed
- [ ] I used AI for code, documentation, tests, or communication related to this PR

### CODE REVIEW

**Comment by arkid15r** [comment]
@cubic-dev-ai review this pull request

File: frontend/src/server/queries/repositoryQueries.ts [hunk 1]
```diff
@@ -23,6 +23,7 @@ export const GET_REPOSITORY_DATA = gql`
         repositoryName
         createdAt
         title
+        url
```
Comment (kasya) [inline frontend/src/server/queries/repositoryQueries.ts]: @anurag2787 is this change relevant to this PR? 🤔

Comment (anurag2787) [reply frontend/src/server/queries/repositoryQueries.ts]: Hi @kasya the url isn’t used directly in this page the issues array is passed to the DetailsCard component (line 110), which receives the full Issue object. The url field is part of that type and is used there to render clickable links for each issue.

If we remove url we will get this error
image
