### PR TITLE
Issue resolved : #1068 Correction to overflow of name in usercard 

### LINKED ISSUE #1068: UI Improvement: The name overflows the div container
**Describe the bug**
The name overflows the div container.

**To Reproduce**

1. Go to https://nest.owasp.dev/community/users
2. search for huntr
3. See error

**Expected behavior**
The name should not overflow and go break to next line or should truncate if too long.
**Are you going to work on fixing this?**

- [x] Yes
- [ ] NO
**Screenshots**
Image

Proposed Solution:
Any one of these solution as per the maintainers wish would be finalised for the PR.
Image

Image

**Smartphone (please complete the following information):**

**Additional context**
I have proposed 2 solutions above any one suggested by the maintainers can be finalised for the PR.

### PR DESCRIPTION
**Pull request by KaranNegi20Feb**
Resolves #1068 UI Improvement: The name overflows the div container. 
 Here's the corrected version of the usercard:

Screenshot 2025-03-10 at 10 34 34 PM

### CODE REVIEW

**Comment by KaranNegi20Feb** [comment]
Hey @arkid15r i have made the required changes please go through those, Thank you 😊.

File: frontend/src/components/UserCard.tsx [hunk 1]
```diff
@@ -24,7 +24,7 @@ const UserCard = ({ avatar, name, company, button }: UserCardProps) => {
         </div>
 
         <div className="text-center">
-          <h3 className="line-clamp-1 text-lg font-semibold text-gray-900 group-hover:text-blue-500 dark:text-white sm:text-xl">
+          <h3 className="whitespace-normal break-words text-lg font-semibold text-gray-900 group-hover:text-blue-500 dark:text-white sm:text-xl">
```
Comment (arkid15r) [inline frontend/src/components/UserCard.tsx]: Let's make it truncated (take just one line) and improve this card with the following logic: show person's company or location or email at the second line. Please also make sure the long content lines are also truncated with `...`

**Review by arkid15r — CHANGES_REQUESTED** [review]
Looks good, could you improve it a bit?

File: frontend/src/components/UserCard.tsx (hunk 1 above)
Comment (KaranNegi20Feb) [reply frontend/src/components/UserCard.tsx]: Screenshot 2025-03-10 at 8 17 39 PM
i think this works?

Comment (arkid15r) [reply frontend/src/components/UserCard.tsx]: This works, could you respond to the rest of my suggestions?

Comment (KaranNegi20Feb) [reply frontend/src/components/UserCard.tsx]: Screenshot 2025-03-10 at 11 52 57 PM
Screenshot 2025-03-10 at 11 52 45 PM
added mail and location

**Review by arkid15r — APPROVED** [review]
LGTM
