### PR TITLE
Fixes #1272  fixing Contributors , tooltip fix and user logo

### LINKED ISSUE #1272: Tool tip issue on New Projects and New Chapters
Mentioned here: https://github.com/OWASP/Nest/pull/1260#issuecomment-2773197639
Also fixed the columns for Top Contributors.

**Are you going to work on fixing this?**

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by KaranNegi20Feb**
Fixes issue:Tool tip issue on New Projects and New Chapters #1272

Screenshot 2025-04-03 at 12 23 22 AM
Screenshot 2025-04-03 at 12 35 30 AM
Screenshot 2025-04-03 at 12 35 39 AM

### CODE REVIEW

**Comment by KaranNegi20Feb** [comment]
Screenshot 2025-04-03 at 1 17 07 AM
All corrections can be checked here @arkid15r, Thank you for reviewing.

**Review by arkid15r — COMMENTED** [review]
It now takes 2 lines instead of 1.
Screenshot 2025-04-02 at 5 58 35 PM

File: frontend/src/pages/Home.tsx [hunk 1]
```diff
@@ -200,7 +200,7 @@ export default function Home() {
                   </div>
 
                   {chapter.leaders.length > 0 && (
-                    <div className="mr-4 mt-1 flex items-center gap-x-2 text-sm [&_a]:text-gray-600 dark:[&_a]:text-gray-400">
```
Comment (kasya) [inline frontend/src/pages/Home.tsx:203]: Why did you remove these? It was targeting specifically `<a>` tags before, but now it's for all text.

**Comment by KaranNegi20Feb** [comment]
Seems like using the older component wasn't a good idea, let me change it again.

File: frontend/src/pages/Home.tsx (hunk 1 above)
Comment (KaranNegi20Feb) [reply frontend/src/pages/Home.tsx:203]: Yeah actually that's the whole point of solving the issue, it was forgetting the , as they were still white and the logo too was white.

**Comment by KaranNegi20Feb** [comment]
Screenshot 2025-04-03 at 9 32 59 AM
Sorry for the inconvenience guys, using the old Tailwind wasn't a good idea, alright it works now.

File: frontend/src/pages/Home.tsx (hunk 1 above)
Comment (KaranNegi20Feb) [reply frontend/src/pages/Home.tsx:203]: The commas were still white and the user icon was white too.

**Review by arkid15r — APPROVED** [review]
LGTM
